// Generated from context/miningpool-assets/pools.json.
// Keep this in sync with the explorer mining pool assets.
pub struct MiningPoolDefinition {
    pub id: u16,
    pub name: &'static str,
    pub slug: &'static str,
    pub link: Option<&'static str>,
    pub addresses: &'static [&'static str],
    pub tags: &'static [&'static str],
}

pub const MINING_POOL_DEFINITIONS: &[MiningPoolDefinition] = &[
    MiningPoolDefinition {
        id: 1,
        name: "BlockFills",
        slug: "blockfills",
        link: Some("https://www.blockfills.com/mining"),
        addresses: &["1PzVut5X6Nx7Mv4JHHKPtVM9Jr9LJ4Rbry"],
        tags: &["/BlockfillsPool/"],
    },
    MiningPoolDefinition {
        id: 2,
        name: "ULTIMUSPOOL",
        slug: "ultimuspool",
        link: Some("https://www.ultimuspool.com"),
        addresses: &["1EMVSMe1VJUuqv7D7SFzctnVXk4KdjXATi", "3C9sAKXrBVpJVe3b738yik4LPHpPmceBgd"],
        tags: &["/ultimus/"],
    },
    MiningPoolDefinition {
        id: 3,
        name: "Terra Pool",
        slug: "terrapool",
        link: Some("https://terrapool.io"),
        addresses: &[
            "32P5KVSbZYAkVmSHxDd2oBXaSk372rbV7L",
            "3Qqp7LwxmSjPwRaKkDToysJsM3xA4ThqFk",
            "bc1q39dled8an7enuxtmjql3pk7ny8kzvsxhd924sl",
        ],
        tags: &["terrapool.io", "Validated with Clean Energy"],
    },
    MiningPoolDefinition {
        id: 4,
        name: "Luxor",
        slug: "luxor",
        link: Some("https://mining.luxor.tech"),
        addresses: &[
            "1MkCDCzHpBsYQivp8MxjY5AkTGG1f2baoe",
            "39bitUyBcUu3y3hRTtYprKbTp712t4ZWqK",
            "32BfKjhByDSxx3BM5vUkQ3NQq9csZR6nt6",
        ],
        tags: &["/LUXOR/", "Luxor Tech"],
    },
    MiningPoolDefinition {
        id: 5,
        name: "1THash",
        slug: "1thash",
        link: Some("https://www.1thash.top"),
        addresses: &["147SwRQdpCfj5p8PnfsXV2SsVVpVcz3aPq", "15vgygQ7ZsWdvZpctmTZK4673QBHsos6Sh"],
        tags: &["/1THash&58COIN/", "/1THash/"],
    },
    MiningPoolDefinition {
        id: 6,
        name: "BTC.com",
        slug: "btccom",
        link: Some("https://pool.btc.com"),
        addresses: &[
            "1Bf9sZvBHPFGVPX71WX2njhd1NXKv5y7v5",
            "34qkc2iac6RsyxZVfyE2S5U5WcRsbg2dpK",
            "3EhLZarJUNSfV6TWMZY1Nh5mi3FMsdHa5U",
            "3NA8hsjfdgVkmmVS9moHmkZsVCoLxUkvvv",
            "bc1qjl8uwezzlech723lpnyuza0h2cdkvxvh54v3dn",
        ],
        tags: &["/BTC.COM/", "/BTC.com/", "btccom"],
    },
    MiningPoolDefinition {
        id: 7,
        name: "Bitfarms",
        slug: "bitfarms",
        link: Some("https://www.bitfarms.io"),
        addresses: &["3GvEGtnvgeBJ3p3EpdZhvUkxY4pDARkbjd"],
        tags: &["BITFARMS"],
    },
    MiningPoolDefinition {
        id: 8,
        name: "Huobi.pool",
        slug: "huobipool",
        link: Some("https://www.hpt.com"),
        addresses: &[
            "18Zcyxqna6h7Z7bRjhKvGpr8HSfieQWXqj",
            "1EepjXgvWUoRyNvuLSAxjiqZ1QqKGDANLW",
            "1MvYASoHjqynMaMnP7SBmenyEWiLsTqoU6",
            "3HuobiNg2wHjdPU2mQczL9on8WF7hZmaGd",
        ],
        tags: &["/HuoBi/", "/Huobi/"],
    },
    MiningPoolDefinition {
        id: 9,
        name: "WAYI.CN",
        slug: "wayicn",
        link: Some("https://www.easy2mine.com"),
        addresses: &[],
        tags: &["/E2M & BTC.TOP/"],
    },
    MiningPoolDefinition {
        id: 10,
        name: "CanoePool",
        slug: "canoepool",
        link: Some("https://btc.canoepool.com"),
        addresses: &["1GP8eWArgpwRum76saJS4cZKCHWJHs9PQo"],
        tags: &["/CANOE/", "/canoepool/"],
    },
    MiningPoolDefinition {
        id: 11,
        name: "BTC.TOP",
        slug: "btctop",
        link: Some("https://btc.top"),
        addresses: &["1Hz96kJKF2HLPGY15JWLB5m9qGNxvt8tHJ"],
        tags: &["/BTC.TOP/"],
    },
    MiningPoolDefinition {
        id: 12,
        name: "Bitcoin.com",
        slug: "bitcoincom",
        link: Some("https://www.bitcoin.com"),
        addresses: &[],
        tags: &["pool.bitcoin.com"],
    },
    MiningPoolDefinition {
        id: 13,
        name: "175btc",
        slug: "175btc",
        link: Some("https://www.175btc.com"),
        addresses: &[],
        tags: &["Mined By 175btc.com"],
    },
    MiningPoolDefinition {
        id: 14,
        name: "GBMiners",
        slug: "gbminers",
        link: Some("https://gbminers.com"),
        addresses: &[],
        tags: &["/mined by gbminers/"],
    },
    MiningPoolDefinition {
        id: 15,
        name: "A-XBT",
        slug: "axbt",
        link: Some("https://www.a-xbt.com"),
        addresses: &["1MFsp2txCPwMMBJjNNeKaduGGs8Wi1Ce7X"],
        tags: &["/A-XBT/"],
    },
    MiningPoolDefinition {
        id: 16,
        name: "ASICMiner",
        slug: "asicminer",
        link: Some("https://www.asicminer.co"),
        addresses: &[],
        tags: &["ASICMiner"],
    },
    MiningPoolDefinition {
        id: 17,
        name: "BitMinter",
        slug: "bitminter",
        link: Some("https://bitminter.com"),
        addresses: &["19PkHafEN18mquJ9ChwZt5YEFoCdPP5vYB"],
        tags: &["BitMinter"],
    },
    MiningPoolDefinition {
        id: 18,
        name: "BitcoinRussia",
        slug: "bitcoinrussia",
        link: Some("https://bitcoin-russia.ru"),
        addresses: &["14R2r9FkyDmyxGB9xUVwVLdgsX9YfdVamk", "165GCEAx81wce33FWEnPCRhdjcXCrBJdKn"],
        tags: &["/Bitcoin-Russia.ru/"],
    },
    MiningPoolDefinition {
        id: 19,
        name: "BTCServ",
        slug: "btcserv",
        link: Some("https://btcserv.net"),
        addresses: &[],
        tags: &["btcserv"],
    },
    MiningPoolDefinition {
        id: 20,
        name: "simplecoin.us",
        slug: "simplecoinus",
        link: Some("https://simplecoin.us"),
        addresses: &[],
        tags: &["simplecoin"],
    },
    MiningPoolDefinition {
        id: 21,
        name: "BTC Guild",
        slug: "btcguild",
        link: Some("https://www.btcguild.com"),
        addresses: &[],
        tags: &["BTC Guild"],
    },
    MiningPoolDefinition {
        id: 22,
        name: "Eligius",
        slug: "eligius",
        link: Some("https://eligius.st"),
        addresses: &[],
        tags: &["Eligius"],
    },
    MiningPoolDefinition {
        id: 23,
        name: "OzCoin",
        slug: "ozcoin",
        link: Some("https://ozcoin.net"),
        addresses: &[],
        tags: &["ozco.in", "ozcoin"],
    },
    MiningPoolDefinition {
        id: 24,
        name: "EclipseMC",
        slug: "eclipsemc",
        link: Some("https://eclipsemc.com"),
        addresses: &["15xiShqUqerfjFdyfgBH1K7Gwp6cbYmsTW", "18M9o2mXNjNR96yKe7eyY6pfP6Nx4Nso3d"],
        tags: &["EMC ", "EMC:"],
    },
    MiningPoolDefinition {
        id: 25,
        name: "MaxBTC",
        slug: "maxbtc",
        link: Some("https://maxbtc.com"),
        addresses: &[],
        tags: &["MaxBTC"],
    },
    MiningPoolDefinition {
        id: 26,
        name: "TripleMining",
        slug: "triplemining",
        link: Some("https://www.triplemining.com"),
        addresses: &[],
        tags: &["Triplemining.com", "triplemining"],
    },
    MiningPoolDefinition {
        id: 27,
        name: "CoinLab",
        slug: "coinlab",
        link: Some("https://coinlab.com"),
        addresses: &[],
        tags: &["CoinLab"],
    },
    MiningPoolDefinition {
        id: 28,
        name: "50BTC",
        slug: "50btc",
        link: Some("https://www.50btc.com"),
        addresses: &[],
        tags: &["50BTC"],
    },
    MiningPoolDefinition {
        id: 29,
        name: "GHash.IO",
        slug: "ghashio",
        link: Some("https://ghash.io"),
        addresses: &["1CjPR7Z5ZSyWk6WtXvSFgkptmpoi4UM9BC"],
        tags: &["ghash.io"],
    },
    MiningPoolDefinition {
        id: 30,
        name: "ST Mining Corp",
        slug: "stminingcorp",
        link: Some("https://bitcointalk.org/index.php?topic=77000.msg3207708#msg3207708"),
        addresses: &[],
        tags: &["st mining corp"],
    },
    MiningPoolDefinition {
        id: 31,
        name: "Bitparking",
        slug: "bitparking",
        link: Some("https://mmpool.bitparking.com"),
        addresses: &[],
        tags: &["bitparking"],
    },
    MiningPoolDefinition {
        id: 32,
        name: "mmpool",
        slug: "mmpool",
        link: Some("https://mmpool.org/pool"),
        addresses: &[],
        tags: &["mmpool"],
    },
    MiningPoolDefinition {
        id: 33,
        name: "Polmine",
        slug: "polmine",
        link: Some("https://polmine.pl"),
        addresses: &[
            "13vWXwzNF5Ef9SUXNTdr7de7MqiV4G1gnL",
            "16cv7wyeG6RRqhvJpY21CnsjxuKj2gAoK2",
            "17kkmDx8eSwj2JTTULb3HkJhCmexfysExz",
            "1AajKXkaq2DsnDmP8ZPTrE5gH1HFo1x3AU",
            "1JrYhdhP2jCY6JwuVzdk9jUwc4pctcSes7",
            "1Nsvmnv8VcTMD643xMYAo35Aco3XA5YPpe",
        ],
        tags: &["by polmine.pl", "bypmneU"],
    },
    MiningPoolDefinition {
        id: 34,
        name: "KnCMiner",
        slug: "kncminer",
        link: Some("https://portal.kncminer.com/pool"),
        addresses: &[],
        tags: &["KnCMiner"],
    },
    MiningPoolDefinition {
        id: 35,
        name: "Bitalo",
        slug: "bitalo",
        link: Some("https://bitalo.com/mining"),
        addresses: &["1HTejfsPZQGi3afCMEZTn2xdmoNzp13n3F"],
        tags: &["Bitalo"],
    },
    MiningPoolDefinition {
        id: 36,
        name: "F2Pool",
        slug: "f2pool",
        link: Some("https://www.f2pool.com"),
        addresses: &[
            "1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY",
            "bc1qf274x7penhcd8hsv3jcmwa5xxzjl2a6pa9pxwm",
        ],
        tags: &["\u{4e03}\u{5f69}\u{795e}\u{4ed9}\u{9c7c}", "F2Pool", "\u{1f41f}"],
    },
    MiningPoolDefinition {
        id: 37,
        name: "HHTT",
        slug: "hhtt",
        link: Some("https://hhtt.1209k.com"),
        addresses: &[],
        tags: &["HHTT"],
    },
    MiningPoolDefinition {
        id: 38,
        name: "MegaBigPower",
        slug: "megabigpower",
        link: Some("https://megabigpower.com"),
        addresses: &["1K7znxRfkS8R1hcmyMvHDum1hAQreS4VQ4"],
        tags: &["megabigpower.com"],
    },
    MiningPoolDefinition {
        id: 39,
        name: "Mt Red",
        slug: "mtred",
        link: Some("https://mtred.com"),
        addresses: &[],
        tags: &["/mtred/"],
    },
    MiningPoolDefinition {
        id: 40,
        name: "NMCbit",
        slug: "nmcbit",
        link: Some("https://nmcbit.com"),
        addresses: &[],
        tags: &["nmcbit.com"],
    },
    MiningPoolDefinition {
        id: 41,
        name: "Yourbtc.net",
        slug: "yourbtcnet",
        link: Some("https://yourbtc.net"),
        addresses: &[],
        tags: &["yourbtc.net"],
    },
    MiningPoolDefinition {
        id: 42,
        name: "Give Me Coins",
        slug: "givemecoins",
        link: Some("https://give-me-coins.com"),
        addresses: &[],
        tags: &["Give-Me-Coins"],
    },
    MiningPoolDefinition {
        id: 43,
        name: "Braiins Pool",
        slug: "braiinspool",
        link: Some("https://braiins.com/pool"),
        addresses: &["1AqTMY7kmHZxBuLUR5wJjPFUvqGs23sesr", "1CK6KHY6MHgYvmRQ4PAafKYDrg1ejbH1cE"],
        tags: &["/slush/"],
    },
    MiningPoolDefinition {
        id: 44,
        name: "AntPool",
        slug: "antpool",
        link: Some("https://www.antpool.com"),
        addresses: &[
            "12dRugNcdxK39288NjcDV4GX7rMsKCGn6B",
            "15kiNKfDWsq7UsPg87UwxA8rVvWAjzRkYS",
            "16MdTdqmXusauybtXTmFEW4GNFPPgGxQYE",
            "16kUc5B48qnASbxeZTisCqTNx6G3DPXuKn",
            "17gVZssumiJqYMCHozHKXGyaAvyu6NCX6V",
            "1AJQ3jXhUF8WiisEcuVd8Xmfq4QJ7n1SdL",
            "1B7ZBX2C39b26M9chHLURGSFTJA6DDQkZv",
            "1BWW3pg5jb6rxebrNeo9TATarwJ1rthnoe",
            "1CBqo1w3hmm9SCmbu2Yg6Ls4uLfkUqZJsx",
            "1CZHhV67Qos4xXb8uYqvAGjK8Wq52woPi5",
            "1CyB8GJNEsNVXtPutB36nrDY3fMXBTzXSX",
            "1D4UZG4qo8bF1MuZHSEyBHRZaxT8inatXS",
            "1D9jw3QHNankXxtcGVihsDK7Z7THN6j7Pg",
            "1DDXyKUT6q3H9e5QXm2Gv6BNNWgztFG55g",
            "1DQaDTefKPjHz3beLuo8KHRZF9t2Sc6foP",
            "1Dek9ArRHb9tyWb9gaaX8SWmkfi5V7U5Y6",
            "1DyR7HPQWjM6Zrnk7SzHVY2GEpXRGNNH9o",
            "1FdJkPdpXtK3t5utZHJAop3saLZWfPfgak",
            "1FrHkVsW7csAYYaRbUUcrKSmv91hcQnsqQ",
            "1GEG1JR81jvUXs7TMAuo3SPBHZrpJijcjt",
            "1GRcX882sdBYCAWyG99iF2oz7j3nYzXhLM",
            "1GT2N4dCufvbnTKMbS61QrQPN4SexCAFiH",
            "1Gp7iCzDGMZiV55Kt8uKsux6VyoHe1aJaN",
            "1H3u6R813MHGYhmGW6v86EYYriawRtACYD",
            "1H6ckqNWikmVT3wpN3X1BQ6b156Xc9nT2L",
            "1JBVrhSSDrZrRmm4RnoWouqgGGqJMvWHi8",
            "1JwUDWVSbAY5NeCBJhxQk1E8AfETfZuPj4",
            "1K8PNogxBZ6ts532DZnzxdbjgzJLjLdXqz",
            "1KmgBTL7cFmFFYTD7HcdkMcZXRcTkh2WwS",
            "1LTGvTjDxiy5S9YcKEE9Lb7xSpZcPSqinw",
            "1MiQrT5sEKTUGNMbd9WS3yPPkSjWdpYA2r",
            "1NS4gbx1G2D5rc9PnvVsPys12nKxGiQg72",
            "1Nh7uHdvY6fNwtQtM1G5EZAFPLC33B59rB",
            "1Pzf7qT7bBGouvnjRvtRD8VhTyqjX1NrJT",
            "1Sjj2cPC3rTWcSTEYDeu2f3BavLosog4T",
            "1jLVpwtNMfXWaHY4eiLDmGuBxokYLgv1X",
            "3FaYVQF6wCMUB9NCeRe4tUp1zZx8qqM7H1",
        ],
        tags: &["/AntPool/", "Mined By AntPool", "Mined by AntPool"],
    },
    MiningPoolDefinition {
        id: 45,
        name: "MultiCoin.co",
        slug: "multicoinco",
        link: Some("https://multicoin.co"),
        addresses: &[],
        tags: &["Mined by MultiCoin.co"],
    },
    MiningPoolDefinition {
        id: 46,
        name: "bcpool.io",
        slug: "bcpoolio",
        link: Some("https://bcpool.io"),
        addresses: &[],
        tags: &["bcpool.io"],
    },
    MiningPoolDefinition {
        id: 47,
        name: "Cointerra",
        slug: "cointerra",
        link: Some("https://cointerra.com"),
        addresses: &["1BX5YoLwvqzvVwSrdD4dC32vbouHQn2tuF"],
        tags: &["cointerra"],
    },
    MiningPoolDefinition {
        id: 48,
        name: "KanoPool",
        slug: "kanopool",
        link: Some("https://kano.is"),
        addresses: &[],
        tags: &["Kano"],
    },
    MiningPoolDefinition {
        id: 49,
        name: "Solo CK",
        slug: "solock",
        link: Some("https://solo.ckpool.org"),
        addresses: &[],
        tags: &["/solo.ckpool.org/"],
    },
    MiningPoolDefinition {
        id: 50,
        name: "CKPool",
        slug: "ckpool",
        link: Some("https://ckpool.org"),
        addresses: &[],
        tags: &["/ckpool.org/"],
    },
    MiningPoolDefinition {
        id: 51,
        name: "NiceHash",
        slug: "nicehash",
        link: Some("https://www.nicehash.com"),
        addresses: &[],
        tags: &["/NiceHashSolo", "/NiceHash/", "/NiceHashMining/"],
    },
    MiningPoolDefinition {
        id: 52,
        name: "BitClub",
        slug: "bitclub",
        link: Some("https://bitclubpool.com"),
        addresses: &["155fzsEBHy9Ri2bMQ8uuuR3tv1YzcDywd4"],
        tags: &["/BitClub Network/"],
    },
    MiningPoolDefinition {
        id: 53,
        name: "Bitcoin Affiliate Network",
        slug: "bitcoinaffiliatenetwork",
        link: Some("https://mining.bitcoinaffiliatenetwork.com"),
        addresses: &[],
        tags: &["bitcoinaffiliatenetwork.com"],
    },
    MiningPoolDefinition {
        id: 54,
        name: "BTCC",
        slug: "btcc",
        link: Some("https://pool.btcc.com"),
        addresses: &["152f1muMCNa7goXYhYAQC61hxEgGacmncB"],
        tags: &["/BTCC/", "BTCChina Pool", "BTCChina.com", "btcchina.com"],
    },
    MiningPoolDefinition {
        id: 55,
        name: "BWPool",
        slug: "bwpool",
        link: Some("https://bwpool.net"),
        addresses: &["1JLRXD8rjRgQtTS9MvfQALfHgGWau9L9ky"],
        tags: &["BW Pool", "BWPool"],
    },
    MiningPoolDefinition {
        id: 56,
        name: "EXX&BW",
        slug: "exxbw",
        link: Some("https://xbtc.exx.com"),
        addresses: &[],
        tags: &["xbtc.exx.com&bw.com"],
    },
    MiningPoolDefinition {
        id: 57,
        name: "Bitsolo",
        slug: "bitsolo",
        link: Some("https://bitsolo.net"),
        addresses: &["18zRehBcA2YkYvsC7dfQiFJNyjmWvXsvon"],
        tags: &["Bitsolo Pool"],
    },
    MiningPoolDefinition {
        id: 58,
        name: "BitFury",
        slug: "bitfury",
        link: Some("https://bitfury.com"),
        addresses: &["14yfxkcpHnju97pecpM7fjuTkVdtbkcfE6", "1AcAj9p6zJn4xLXdvmdiuPCtY7YkBPTAJo"],
        tags: &["/BitFury/", "/Bitfury/"],
    },
    MiningPoolDefinition {
        id: 59,
        name: "21 Inc.",
        slug: "21inc",
        link: Some("https://21.co"),
        addresses: &[
            "15rQXUSBQRubShPpiJfDLxmwS8ze2RUm4z",
            "1CdJi2xRTXJF6CEJqNHYyQDNEcM3X7fUhD",
            "1GC6HxDvnchDdb5cGkFXsJMZBFRsKAXfwi",
        ],
        tags: &["/pool34/"],
    },
    MiningPoolDefinition {
        id: 60,
        name: "digitalBTC",
        slug: "digitalbtc",
        link: Some("https://digitalbtc.com"),
        addresses: &["1MimPd6LrPKGftPRHWdfk8S3KYBfN4ELnD"],
        tags: &["/agentD/"],
    },
    MiningPoolDefinition {
        id: 61,
        name: "8baochi",
        slug: "8baochi",
        link: Some("https://8baochi.com"),
        addresses: &["1Hk9gD8xMo2XBUhE73y5zXEM8xqgffTB5f"],
        tags: &["/\u{516b}\u{5b9d}\u{6c60} 8baochi.com/"],
    },
    MiningPoolDefinition {
        id: 62,
        name: "myBTCcoin Pool",
        slug: "mybtccoinpool",
        link: Some("https://mybtccoin.com"),
        addresses: &["151T7r1MhizzJV6dskzzUkUdr7V8JxV2Dx"],
        tags: &["myBTCcoin Pool"],
    },
    MiningPoolDefinition {
        id: 63,
        name: "TBDice",
        slug: "tbdice",
        link: Some("https://tbdice.org"),
        addresses: &["1BUiW44WuJ2jiJgXiyxJVFMN8bc1GLdXRk"],
        tags: &["TBDice"],
    },
    MiningPoolDefinition {
        id: 64,
        name: "HASHPOOL",
        slug: "hashpool",
        link: Some("https://hashpool.com"),
        addresses: &[],
        tags: &["HASHPOOL"],
    },
    MiningPoolDefinition {
        id: 65,
        name: "Nexious",
        slug: "nexious",
        link: Some("https://nexious.com"),
        addresses: &["1GBo1f2tzVx5jScV9kJXPUP9RjvYXuNzV7"],
        tags: &["/Nexious/"],
    },
    MiningPoolDefinition {
        id: 66,
        name: "Bravo Mining",
        slug: "bravomining",
        link: Some("https://www.bravo-mining.com"),
        addresses: &[],
        tags: &["/bravo-mining/"],
    },
    MiningPoolDefinition {
        id: 67,
        name: "HotPool",
        slug: "hotpool",
        link: Some("https://hotpool.co"),
        addresses: &["17judvK4AC2M6KhaBbAEGw8CTKc9Pg8wup"],
        tags: &["/HotPool/"],
    },
    MiningPoolDefinition {
        id: 68,
        name: "OKExPool",
        slug: "okexpool",
        link: Some("https://www.okex.com"),
        addresses: &[],
        tags: &["/www.okex.com/"],
    },
    MiningPoolDefinition {
        id: 69,
        name: "BCMonster",
        slug: "bcmonster",
        link: Some("https://www.bcmonster.com"),
        addresses: &["1E18BNyobcoiejcDYAz5SjbrzifNDEpM88"],
        tags: &["/BCMonster/"],
    },
    MiningPoolDefinition {
        id: 70,
        name: "1Hash",
        slug: "1hash",
        link: Some("https://www.1hash.com"),
        addresses: &["1F1xcRt8H8Wa623KqmkEontwAAVqDSAWCV"],
        tags: &["Mined by 1hash.com"],
    },
    MiningPoolDefinition {
        id: 71,
        name: "Bixin",
        slug: "bixin",
        link: Some("https://haopool.com"),
        addresses: &["13hQVEstgo4iPQZv9C7VELnLWF7UWtF4Q3", "1KsFhYKLs8qb1GHqrPxHoywNQpet2CtP9t"],
        tags: &["/Bixin/", "/HaoBTC/", "HAOBTC"],
    },
    MiningPoolDefinition {
        id: 72,
        name: "TATMAS Pool",
        slug: "tatmaspool",
        link: Some("https://tmsminer.com"),
        addresses: &[],
        tags: &["/ViaBTC/TATMAS Pool/"],
    },
    MiningPoolDefinition {
        id: 73,
        name: "ViaBTC",
        slug: "viabtc",
        link: Some("https://viabtc.com"),
        addresses: &[],
        tags: &["/ViaBTC/", "viabtc.com deploy"],
    },
    MiningPoolDefinition {
        id: 74,
        name: "ConnectBTC",
        slug: "connectbtc",
        link: Some("https://www.connectbtc.com"),
        addresses: &["1KPQkehgYAqwiC6UCcbojM3mbGjURrQJF2"],
        tags: &["/ConnectBTC - Home for Miners/"],
    },
    MiningPoolDefinition {
        id: 75,
        name: "BATPOOL",
        slug: "batpool",
        link: Some("https://www.batpool.com"),
        addresses: &["167ApWWxUSFQmz2jdz9xop3oAKdLejvMML"],
        tags: &["/BATPOOL/"],
    },
    MiningPoolDefinition {
        id: 76,
        name: "Waterhole",
        slug: "waterhole",
        link: Some("https://btc.waterhole.io"),
        addresses: &["1FLH1SoLv4U68yUERhDiWzrJn5TggMqkaZ"],
        tags: &["/WATERHOLE.IO/"],
    },
    MiningPoolDefinition {
        id: 77,
        name: "DCExploration",
        slug: "dcexploration",
        link: Some("https://dcexploration.cn"),
        addresses: &[],
        tags: &["/DCExploration/"],
    },
    MiningPoolDefinition {
        id: 78,
        name: "DCEX",
        slug: "dcex",
        link: Some("https://dcexploration.cn"),
        addresses: &[],
        tags: &["/DCEX/"],
    },
    MiningPoolDefinition {
        id: 79,
        name: "BTPOOL",
        slug: "btpool",
        link: None,
        addresses: &[],
        tags: &["/BTPOOL/"],
    },
    MiningPoolDefinition {
        id: 80,
        name: "58COIN",
        slug: "58coin",
        link: Some("https://www.58coin.com"),
        addresses: &["199EDJoCpqV672qESEkfFgEqNT1iR2gj3t"],
        tags: &["/58coin.com/"],
    },
    MiningPoolDefinition {
        id: 81,
        name: "Bitcoin India",
        slug: "bitcoinindia",
        link: Some("https://bitcoin-india.org"),
        addresses: &[],
        tags: &["/Bitcoin-India/"],
    },
    MiningPoolDefinition {
        id: 82,
        name: "shawnp0wers",
        slug: "shawnp0wers",
        link: Some("https://www.brainofshawn.com"),
        addresses: &["12znnESiJ3bgCLftwwrg9wzQKN8fJtoBDa", "18HEMWFXM9UGPVZHUMdBPD3CMFWYn2NPRX"],
        tags: &["--Nug--"],
    },
    MiningPoolDefinition {
        id: 83,
        name: "PHash.IO",
        slug: "phashio",
        link: Some("https://phash.io"),
        addresses: &[],
        tags: &["/phash.cn/", "/phash.io/"],
    },
    MiningPoolDefinition {
        id: 84,
        name: "RigPool",
        slug: "rigpool",
        link: Some("https://www.rigpool.com"),
        addresses: &["1JpKmtspBJQVXK67DJP64eBJcAPhDvJ9Er"],
        tags: &["/RigPool.com/"],
    },
    MiningPoolDefinition {
        id: 85,
        name: "HAOZHUZHU",
        slug: "haozhuzhu",
        link: Some("https://haozhuzhu.com"),
        addresses: &["19qa95rTbDziNCS9EexUbh2hVY4viUU9tt"],
        tags: &["/haozhuzhu/"],
    },
    MiningPoolDefinition {
        id: 86,
        name: "7pool",
        slug: "7pool",
        link: Some("https://7pool.com"),
        addresses: &["1JLc3JxvpdL1g5zoX8sKLP4BkJQiwnJftU"],
        tags: &["/$Mined by 7pool.com/"],
    },
    MiningPoolDefinition {
        id: 87,
        name: "MiningKings",
        slug: "miningkings",
        link: Some("https://miningkings.com"),
        addresses: &[
            "1ApE99VM5RJzMRRtwd2JMgmkGabtJqoMEz",
            "1EowSPumj9D9AMTpE64Jr7vT3PJDNopVcz",
            "1KGbsDDAgJN2HDNBjmMHp9828qATo5B9c9",
        ],
        tags: &["/mined by poopbut/"],
    },
    MiningPoolDefinition {
        id: 88,
        name: "HashBX",
        slug: "hashbx",
        link: Some("https://hashbx.io"),
        addresses: &[],
        tags: &["/Mined by HashBX.io/"],
    },
    MiningPoolDefinition {
        id: 89,
        name: "DPOOL",
        slug: "dpool",
        link: Some("https://www.dpool.top"),
        addresses: &["1ACAgPuFFidYzPMXbiKptSrwT74Dg8hq2v"],
        tags: &["/DPOOL.TOP/"],
    },
    MiningPoolDefinition {
        id: 90,
        name: "Rawpool",
        slug: "rawpool",
        link: Some("https://www.rawpool.com"),
        addresses: &[
            "1FbBbv5oYqFKwiPm4CAqvAy8345n8AQ74b",
            "35y82tEPDa2wm6tzkEacMG8GPPW7zbMj83",
            "3CLigLYNkrtoNgNcUwTaKoUSHCwr9W851W",
            "3QYvfQoG9Gs9Vfvbpw6947muSqhoGagvF6",
            "bc1q8ej2g5uxdsg0jwl0mpl606qfjxgkyv3p29yf37",
            "bc1qnnl503n04cqacpwvhr89qr70metxr79ht3n380",
            "bc1qru8mtv3e3u7ms6ecjmwgeakdakclemvhnw00q9",
            "bc1qwlrsvgtn99rqp3fgaxq6f6jkgms80rnej0a8tc",
        ],
        tags: &["/Rawpool.com/"],
    },
    MiningPoolDefinition {
        id: 91,
        name: "haominer",
        slug: "haominer",
        link: Some("https://haominer.com"),
        addresses: &[],
        tags: &["/haominer/"],
    },
    MiningPoolDefinition {
        id: 92,
        name: "Helix",
        slug: "helix",
        link: None,
        addresses: &[],
        tags: &["/Helix/"],
    },
    MiningPoolDefinition {
        id: 93,
        name: "Bitcoin-Ukraine",
        slug: "bitcoinukraine",
        link: Some("https://bitcoin-ukraine.com.ua"),
        addresses: &[],
        tags: &["/Bitcoin-Ukraine.com.ua/"],
    },
    MiningPoolDefinition {
        id: 94,
        name: "Poolin",
        slug: "poolin",
        link: Some("https://www.poolin.com"),
        addresses: &[
            "14sA8jqYQgMRQV9zUtGFvpeMEw7YDn77SK",
            "17tUZLvy3X2557JGhceXRiij2TNYuhRr4r",
            "1E8CZo2S3CqWg1VZSJNFCTbtT8hZPuQ2kB",
            "1GNgwA8JfG7Kc8akJ8opdNWJUihqUztfPe",
            "36n452uGq1x4mK7bfyZR8wgE47AnBb2pzi",
            "3JQSigWTCHyBLRD979JWgEtWP5YiiFwcQB",
            "3KJrsjfg1dD6CrsTeHdHVH3KqMpvL2XWQn",
        ],
        tags: &["/poolin.com", "/poolin/"],
    },
    MiningPoolDefinition {
        id: 95,
        name: "SecretSuperstar",
        slug: "secretsuperstar",
        link: None,
        addresses: &[],
        tags: &["/SecretSuperstar/"],
    },
    MiningPoolDefinition {
        id: 96,
        name: "tigerpool.net",
        slug: "tigerpoolnet",
        link: None,
        addresses: &[],
        tags: &["/tigerpool.net"],
    },
    MiningPoolDefinition {
        id: 97,
        name: "Sigmapool.com",
        slug: "sigmapoolcom",
        link: Some("https://sigmapool.com"),
        addresses: &["12cKiMNhCtBhZRUBCnYXo8A4WQzMUtYjmR"],
        tags: &["/Sigmapool.com/"],
    },
    MiningPoolDefinition {
        id: 98,
        name: "okpool.top",
        slug: "okpooltop",
        link: Some("https://www.okpool.top"),
        addresses: &[],
        tags: &["/www.okpool.top/"],
    },
    MiningPoolDefinition {
        id: 99,
        name: "Hummerpool",
        slug: "hummerpool",
        link: Some("https://www.hummerpool.com"),
        addresses: &[],
        tags: &["HummerPool", "Hummerpool"],
    },
    MiningPoolDefinition {
        id: 100,
        name: "Tangpool",
        slug: "tangpool",
        link: Some("https://www.tangpool.com"),
        addresses: &["12Taz8FFXQ3E2AGn3ZW1SZM5bLnYGX4xR6"],
        tags: &["/Tangpool/"],
    },
    MiningPoolDefinition {
        id: 101,
        name: "BytePool",
        slug: "bytepool",
        link: Some("https://www.bytepool.com"),
        addresses: &["39m5Wvn9ZqyhYmCYpsyHuGMt5YYw4Vmh1Z"],
        tags: &["/bytepool.com/"],
    },
    MiningPoolDefinition {
        id: 102,
        name: "SpiderPool",
        slug: "spiderpool",
        link: Some("https://www.spiderpool.com"),
        addresses: &[
            "125m2H43pwKpSZjLhMQHneuTwTJN5qRyYu",
            "38u1srayb1oybVB43UWKBJsrwJbdHGtPx2",
            "1BM1sAcrfV6d4zPKytzziu4McLQDsFC2Qc",
        ],
        tags: &["SpiderPool"],
    },
    MiningPoolDefinition {
        id: 103,
        name: "NovaBlock",
        slug: "novablock",
        link: Some("https://novablock.com"),
        addresses: &["3Bmb9Jig8A5kHdDSxvDZ6eryj3AXd3swuJ"],
        tags: &["/NovaBlock/"],
    },
    MiningPoolDefinition {
        id: 104,
        name: "MiningCity",
        slug: "miningcity",
        link: Some("https://www.miningcity.com"),
        addresses: &["11wC5KcbgrWRBb43cwADdVrxgyF8mndVC"],
        tags: &["MiningCity"],
    },
    MiningPoolDefinition {
        id: 105,
        name: "Binance Pool",
        slug: "binancepool",
        link: Some("https://pool.binance.com"),
        addresses: &[
            "122pN8zvqTxJaA8fRY1PDBu4QYodqE5m2X",
            "16moWjUJVRnDQKqhoCdcszfJg9wzBdoTHw",
            "1DSh7vX6ed2cgTeKPwufV5i4hSi4pp373h",
            "1JvXhnHCi6XqcanvrZJ5s2Qiv4tsmm2UMy",
            "3L8Ck6bm3sve1vJGKo6Ht2k167YKSKi8TZ",
            "bc1qx9t2l3pyny2spqpqlye8svce70nppwtaxwdrp4",
            "3G7jcEELKh38L6kaSV8K35pTqsh5bgZW2D",
        ],
        tags: &["/Binance/", "binance"],
    },
    MiningPoolDefinition {
        id: 106,
        name: "Minerium",
        slug: "minerium",
        link: Some("https://www.minerium.com"),
        addresses: &[],
        tags: &["/Mined in the USA by: /Minerium.com/", "/Minerium.com/"],
    },
    MiningPoolDefinition {
        id: 107,
        name: "Lubian.com",
        slug: "lubiancom",
        link: Some("https://www.lubian.com"),
        addresses: &["34Jpa4Eu3ApoPVUKNTN2WeuXVVq1jzxgPi"],
        tags: &["/Buffett/", "/lubian.com/"],
    },
    MiningPoolDefinition {
        id: 108,
        name: "OKKONG",
        slug: "okkong",
        link: Some("https://hash.okkong.com"),
        addresses: &["16JHXJ7M2MubWNX9grnqbjUqJ5PHwcCWw2"],
        tags: &["/hash.okkong.com/"],
    },
    MiningPoolDefinition {
        id: 109,
        name: "AAO Pool",
        slug: "aaopool",
        link: Some("https://btc.tmspool.top"),
        addresses: &["12QVFmJH2b4455YUHkMpEnWLeRY3eJ4Jb5"],
        tags: &["/AAOPOOL/"],
    },
    MiningPoolDefinition {
        id: 110,
        name: "EMCDPool",
        slug: "emcdpool",
        link: Some("https://pool.emcd.io"),
        addresses: &["1BDbsWi3Mrcjp1wdop3PWFNCNZtu4R7Hjy"],
        tags: &["/EMCD/", "/one_more_mcd/", "get___emcd", "emcd"],
    },
    MiningPoolDefinition {
        id: 111,
        name: "Foundry USA",
        slug: "foundryusa",
        link: Some("https://foundrydigital.com"),
        addresses: &[
            "12KKDt4Mj7N5UAkQMN7LtPZMayenXHa8KL",
            "1FFxkVijzvUPUeHgkFjBk2Qw8j3wQY2cDw",
            "bc1qxhmdufsvnuaaaer4ynz88fspdsxq2h9e9cetdj",
            "bc1p8k4v4xuz55dv49svzjg43qjxq2whur7ync9tm0xgl5t4wjl9ca9snxgmlt",
        ],
        tags: &["/2cDw/", "Foundry USA Pool"],
    },
    MiningPoolDefinition {
        id: 112,
        name: "SBI Crypto",
        slug: "sbicrypto",
        link: Some("https://sbicrypto.com"),
        addresses: &[],
        tags: &["/SBICrypto.com Pool/", "SBI Crypto", "SBICrypto"],
    },
    MiningPoolDefinition {
        id: 113,
        name: "ArkPool",
        slug: "arkpool",
        link: Some("https://www.arkpool.com"),
        addresses: &["1QEiAhdHdMhBgVbDM7zUXWGkNhgEEJ6uLd"],
        tags: &["/ArkPool/"],
    },
    MiningPoolDefinition {
        id: 114,
        name: "PureBTC.COM",
        slug: "purebtccom",
        link: Some("https://purebtc.com"),
        addresses: &[],
        tags: &["/PureBTC.COM/"],
    },
    MiningPoolDefinition {
        id: 115,
        name: "MARA Pool",
        slug: "marapool",
        link: Some("https://marapool.com"),
        addresses: &["15MdAHnkxt9TMC2Rj595hsg8Hnv693pPBB", "1A32KFEX7JNPmU1PVjrtiXRrTQcesT3Nf1"],
        tags: &["MARA Pool", "MARA Made in USA"],
    },
    MiningPoolDefinition {
        id: 116,
        name: "KuCoinPool",
        slug: "kucoinpool",
        link: Some("https://www.kucoin.com/mining-pool"),
        addresses: &["1ArTPjj6pV3aNRhLPjJVPYoxB98VLBzUmb"],
        tags: &["KuCoinPool"],
    },
    MiningPoolDefinition {
        id: 117,
        name: "Entrust Charity Pool",
        slug: "entrustcharitypool",
        link: Some("pool.entustus.org"),
        addresses: &[],
        tags: &["Entrustus"],
    },
    MiningPoolDefinition {
        id: 118,
        name: "OKMINER",
        slug: "okminer",
        link: Some("https://okminer.com"),
        addresses: &["15xcAZ2HfaSwYbCV6GGbasBSAekBRRC5Q2"],
        tags: &["okminer.com/euz"],
    },
    MiningPoolDefinition {
        id: 119,
        name: "Titan",
        slug: "titan",
        link: Some("https://titan.io"),
        addresses: &["14hLEtxozmmih6Gg5xrGZLfx51bEMj21NW"],
        tags: &["Titan.io"],
    },
    MiningPoolDefinition {
        id: 120,
        name: "PEGA Pool",
        slug: "pegapool",
        link: Some("https://www.pega-pool.com"),
        addresses: &["1BGFwRzjCfRR7EvRHnzfHyFjGR8XiBDFKa"],
        tags: &["/pegapool/"],
    },
    MiningPoolDefinition {
        id: 121,
        name: "BTC Nuggets",
        slug: "btcnuggets",
        link: Some("https://104.197.8.250"),
        addresses: &["1BwZeHJo7b7M2op7VDfYnsmcpXsUYEcVHm"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 122,
        name: "CloudHashing",
        slug: "cloudhashing",
        link: Some("https://cloudhashing.com"),
        addresses: &["1ALA5v7h49QT7WYLcRsxcXqXUqEqaWmkvw"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 123,
        name: "digitalX Mintsy",
        slug: "digitalxmintsy",
        link: Some("https://www.mintsy.co"),
        addresses: &["1NY15MK947MLzmPUa2gL7UgyR8prLh2xfu"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 124,
        name: "Telco 214",
        slug: "telco214",
        link: Some("https://www.telco214.com"),
        addresses: &[
            "13Sd8Y7nUao3z4bJFkZvCRXpFqHvLy49YY",
            "14M1pQ5KKeqmDrmqKyZEnaxAGJfBPrfWvQ",
            "18hvMLisvfc58PvA5rHH7NsLN9CV5ddB2x",
            "18ikmzPqk721ZNvWhDos1UL4H29w352Kj5",
            "1AsEJU4ht5wR7BzV6xsNQpwi5qRx4qH1ac",
            "1BUhwvF9oo3qkaSjjPpWrUzQxXNjkHdMZF",
            "1CNq2FAw6S5JfBiDkjkYJUVNQwjoeY4Zfi",
            "1DXRoTT67mCbhdHHL1it4J1xsSZHHnFxYR",
            "1GaKSh2t396nfSg5Ku2J3Yn1vfVsXrGuH5",
            "1LXWA3EEEwPixQcyFWXKX2hWHpkDoLknZW",
            "1MoYfV4U61wqTPTHCyedzFmvf2o3uys2Ua",
            "1P4B6rx1js8TaEDXvZvtrkiEb9XrJgMQ19",
        ],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 125,
        name: "BTC Pool Party",
        slug: "btcpoolparty",
        link: Some("https://btcpoolparty.com"),
        addresses: &["1PmRrdp1YSkp1LxPyCfcmBHDEipG5X4eJB"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 126,
        name: "Multipool",
        slug: "multipool",
        link: Some("https://www.multipool.us"),
        addresses: &["1MeffGLauEj2CZ18hRQqUauTXb9JAuLbGw"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 127,
        name: "transactioncoinmining",
        slug: "transactioncoinmining",
        link: Some("https://sha256.transactioncoinmining.com"),
        addresses: &["1qtKetXKgqa7j1KrB19HbvfRiNUncmakk"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 128,
        name: "BTCDig",
        slug: "btcdig",
        link: Some("https://btcdig.com"),
        addresses: &["15MxzsutVroEE9XiDckLxUHTCDAEZgPZJi"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 129,
        name: "Tricky's BTC Pool",
        slug: "trickysbtcpool",
        link: Some("https://pool.wemine.uk"),
        addresses: &["1AePMyovoijxvHuKhTqWvpaAkRCF4QswC6"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 130,
        name: "BTCMP",
        slug: "btcmp",
        link: Some("https://www.btcmp.com"),
        addresses: &["1jKSjMLnDNup6NPgCjveeP9tUn4YpT94Y"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 131,
        name: "Eobot",
        slug: "eobot",
        link: Some("https://eobot.com"),
        addresses: &["16GsNC3q6KgVXkUX7j7aPxSUdHrt1sN2yN", "1MPxhNkSzeTNTHSZAibMaS8HS1esmUL1ne"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 132,
        name: "UNOMP",
        slug: "unomp",
        link: Some("https://199.115.116.7:8925"),
        addresses: &["1BRY8AD7vSNUEE75NjzfgiG18mWjGQSRuJ"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 133,
        name: "Patels",
        slug: "patels",
        link: Some("https://patelsminingpool.com"),
        addresses: &["197miJmttpCt2ubVs6DDtGBYFDroxHmvVB", "19RE4mz2UbDxDVougc6GGdoT4x5yXxwFq2"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 134,
        name: "GoGreenLight",
        slug: "gogreenlight",
        link: Some("https://www.gogreenlight.se"),
        addresses: &["18EPLvrs2UE11kWBB3ABS7Crwj5tTBYPoa"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 135,
        name: "BitcoinIndia",
        slug: "bitcoinindia",
        link: Some("https://pool.bitcoin-india.org"),
        addresses: &["1AZ6BkCo4zgTuuLpRStJH8iNsehXTMp456"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 136,
        name: "EkanemBTC",
        slug: "ekanembtc",
        link: Some("https://ekanembtc.com"),
        addresses: &["1Cs5RT9SRk1hxsdzivAfkjesNmVVJqfqkw"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 137,
        name: "CANOE",
        slug: "canoe",
        link: Some("https://www.canoepool.com"),
        addresses: &["1Afcpc2FpPnREU6i52K3cicmHdvYRAH9Wo"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 138,
        name: "tiger",
        slug: "tiger",
        link: None,
        addresses: &["1LsFmhnne74EmU4q4aobfxfrWY4wfMVd8w"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 139,
        name: "1M1X",
        slug: "1m1x",
        link: None,
        addresses: &["1M1Xw2rczxkF3p3wiNHaTmxvbpZZ7M6vaa"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 140,
        name: "Zulupool",
        slug: "zulupool",
        link: Some("https://beta.zulupool.com/"),
        addresses: &["1ZULUPooLEQfkrTgynLV4uHyMgQYx71ip"],
        tags: &["ZULUPooL", "ZU_test"],
    },
    MiningPoolDefinition {
        id: 141,
        name: "SECPOOL",
        slug: "secpool",
        link: Some("https://www.secpool.com"),
        addresses: &["3Awm3FNpmwrbvAFVThRUFqgpbVuqWisni9"],
        tags: &["SecPool"],
    },
    MiningPoolDefinition {
        id: 142,
        name: "OCEAN",
        slug: "ocean",
        link: Some("https://ocean.xyz/"),
        addresses: &["37dvwZZoT3D7RXpTCpN2yKzMmNs2i2Fd1n"],
        tags: &["OCEAN.XYZ"],
    },
    MiningPoolDefinition {
        id: 143,
        name: "WhitePool",
        slug: "whitepool",
        link: Some("https://whitebit.com/mining-pool"),
        addresses: &["14VkxDwSAUWrzYTxV49HnYhKLWTJ3pCoUS"],
        tags: &["WhitePool"],
    },
    MiningPoolDefinition {
        id: 144,
        name: "wiz",
        slug: "wiz",
        link: Some("https://wiz.biz/"),
        addresses: &[
            "1wizSAYSbuyXbt9d8JV8ytm5acqq2TorC",
            "tb1q548z58kqvwyjqwy8vc2ntmg33d7s2wyfv7ukq4",
        ],
        tags: &["/@wiz/"],
    },
    MiningPoolDefinition {
        id: 145,
        name: "mononaut",
        slug: "mononaut",
        link: Some("https://twitter.com/mononautical"),
        addresses: &["mjP97q5BWtdpdsJLkEJvQWgLe9zw4MMVU6"],
        tags: &["\u{1f435}\u{1f680}"],
    },
    MiningPoolDefinition {
        id: 146,
        name: "rijndael",
        slug: "rijndael",
        link: Some("https://twitter.com/rot13maxi"),
        addresses: &["tb1qg8zlznrvns9u46muxamxjh7sa8wry3vutzaujm"],
        tags: &["rijndael's toaster"],
    },
    MiningPoolDefinition {
        id: 147,
        name: "wk057",
        slug: "wk057",
        link: None,
        addresses: &["1WizkidqARMLvjGUpfDQFRcEbnHpL55kK"],
        tags: &["wizkid057's block"],
    },
    MiningPoolDefinition {
        id: 148,
        name: "FutureBit Apollo Solo",
        slug: "futurebitapollosolo",
        link: Some("https://www.futurebit.io"),
        addresses: &[],
        tags: &["Apollo", "FutureBit", "/mined by a Solo FutureBit Apollo/"],
    },
    MiningPoolDefinition {
        id: 149,
        name: "emzy",
        slug: "emzy",
        link: Some("https://twitter.com/emzy"),
        addresses: &["tb1qmf7xdqc5nvzhturuzc46qtq5kywdf3p76cpq53"],
        tags: &["Emzy was here."],
    },
    MiningPoolDefinition {
        id: 150,
        name: "knorrium",
        slug: "knorrium",
        link: Some("https://twitter.com/knorrium"),
        addresses: &["tb1qtfqp4g7n7wc3sr6c2cuzsq62px4pfsxgsv2krx"],
        tags: &["knorrium"],
    },
    MiningPoolDefinition {
        id: 151,
        name: "Carbon Negative",
        slug: "carbonnegative",
        link: Some("https://github.com/bitcoin-data/mining-pools/issues/48"),
        addresses: &["33SAB6pzbhEGPbfY6NVgRDV7jVfspZ3A3Z", "3KZDwmJHB6QJ13QPXHaW7SS3yTESFPZoxb"],
        tags: &[],
    },
    MiningPoolDefinition {
        id: 152,
        name: "Portland.HODL",
        slug: "portlandhodl",
        link: None,
        addresses: &[],
        tags: &["Portland.HODL"],
    },
    MiningPoolDefinition {
        id: 153,
        name: "Phoenix",
        slug: "phoenix",
        link: Some("https://phoenixpool.com"),
        addresses: &[
            "37cGvBD4qufoZQHopGS7XstxRUzx5cNuy1",
            "bc1q2zcenaujmmdv8sqgf723cug4vjnphkvvf8zpst",
            "1Ld6okoaLNDbSnougAyQTrchxRn9ELnTJg",
        ],
        tags: &["/Phoenix/"],
    },
    MiningPoolDefinition {
        id: 154,
        name: "Neopool",
        slug: "neopool",
        link: Some("https://neopool.com/"),
        addresses: &["1HCAb2h89bUinm6QZrAPpfbk4ySBrT2V4w"],
        tags: &["/Neopool/"],
    },
    MiningPoolDefinition {
        id: 155,
        name: "MaxiPool",
        slug: "maxipool",
        link: Some("https://maxipool.org/"),
        addresses: &["36r3YqAXWpyqNcczjCBdHrYZ3m8X56WDzx"],
        tags: &["/MaxiPool/"],
    },
    MiningPoolDefinition {
        id: 156,
        name: "DrDetroit",
        slug: "drdetroit",
        link: Some("https://x.com/bankhatin"),
        addresses: &["tb1qtcruplnz89xw5f86kw8sj7x9r23d5yffrysx2p"],
        tags: &["DrDetroit"],
    },
    MiningPoolDefinition {
        id: 157,
        name: "BitFuFuPool",
        slug: "bitfufupool",
        link: Some("https://www.bitfufu.com/pool"),
        addresses: &["3JP3zF7LoeoAotqkNGdvX5szUyNPwd937d"],
        tags: &["/BitFuFu/"],
    },
    MiningPoolDefinition {
        id: 158,
        name: "GDPool",
        slug: "gdpool",
        link: None,
        addresses: &["1DnPPFQPrfyNTiHPXhDFyqNnW9T62GEhB1"],
        tags: &["Lucky pool", "GDPool"],
    },
    MiningPoolDefinition {
        id: 159,
        name: "Mining-Dutch",
        slug: "miningdutch",
        link: Some("https://www.mining-dutch.nl/"),
        addresses: &["1AfPSq5ZbqBaxU5QAayLQJMcXV8HZt92eq"],
        tags: &["/Mining-Dutch/"],
    },
    MiningPoolDefinition {
        id: 160,
        name: "Public Pool",
        slug: "publicpool",
        link: Some("https://web.public-pool.io/"),
        addresses: &[],
        tags: &["Public-Pool", "Public Pool on Umbrel"],
    },
    MiningPoolDefinition {
        id: 161,
        name: "Mining Squared",
        slug: "miningsquared",
        link: Some("https://pool.bsquared.network/"),
        addresses: &["3GdjWJdkJhtkxRZ3Ns1LstaoHNMBW8XsvU", "3AvXzTUat4p6Qf6ZLnRNvB3mDLjp3fNmjJ"],
        tags: &["MiningSquared", "BSquared Network", "/bsquared/"],
    },
    MiningPoolDefinition {
        id: 162,
        name: "Innopolis Tech",
        slug: "innopolistech",
        link: Some("https://innopolis.tech/"),
        addresses: &["bc1q75t4wewkmf3l9qg097zvtlh05v5pdz6699kv8k"],
        tags: &["Innopolis", "Innopolis.tech"],
    },
    MiningPoolDefinition {
        id: 163,
        name: "nymkappa",
        slug: "nymkappa",
        link: Some("https://github.com/nymkappa"),
        addresses: &["tb1qdyy39724wqnqqqduv6zxsf56s2ec9lgypxs59h"],
        tags: &["/@nymkappa/"],
    },
    MiningPoolDefinition {
        id: 164,
        name: "BTCLab",
        slug: "btclab",
        link: Some("https://btclab.dev/"),
        addresses: &[],
        tags: &["BTCLab", "BTCLab.dev"],
    },
    MiningPoolDefinition {
        id: 165,
        name: "Parasite",
        slug: "parasite",
        link: Some("https://parasite.space"),
        addresses: &[],
        tags: &["parasite"],
    },
    MiningPoolDefinition {
        id: 166,
        name: "RedRock Pool",
        slug: "redrockpool",
        link: Some("https://redrock.pro/"),
        addresses: &["3554kSaWNnP3B49Xyybert7gmxq2YSnfnx"],
        tags: &["RedRock"],
    },
    MiningPoolDefinition {
        id: 167,
        name: "Est3lar",
        slug: "est3lar",
        link: Some("https://est3lar.io"),
        addresses: &["34qGNFx6uQv6SzjYPbYVWtjvuy5DSGugt8"],
        tags: &["/Est3lar/", "est3lar", "Est3lar", "EST3LAR"],
    },
    MiningPoolDefinition {
        id: 168,
        name: "Braiins Solo",
        slug: "braiinssolo",
        link: Some("https://solo.braiins.com"),
        addresses: &[],
        tags: &["/braiinssolo/"],
    },
    MiningPoolDefinition {
        id: 169,
        name: "SoloPool.com",
        slug: "solopoolcom",
        link: Some("https://solopool.com"),
        addresses: &["bc1qreaftg3lr53nv84dnxhcvchmswevzlp9tdj2jd"],
        tags: &["/Mined @ SoloPool.Com/"],
    },
    MiningPoolDefinition {
        id: 170,
        name: "Noderunners",
        slug: "noderunners",
        link: Some("https://pool.noderunners.network"),
        addresses: &[],
        tags: &["/Noderunners/"],
    },
];
